{{- if .Values.ui.ingress.enabled -}}
{{- $serviceName := .Chart.Name -}}
{{- $servicePort := .Values.ui.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
{{ include "service.labels.standard" . | indent 4 }}
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.ui.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Chart.Name }}
  annotations:
    {{- range $key, $value := .Values.ui.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ui.ingress.hosts }}
      {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ui.ingress.tls }}
  tls:
{{ toYaml .Values.ui.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
