export default {
  0: {
    name: 'Service Dashboard',
    type: 'service',
    children: [{
      name: 'Global',
      children: [{
        d: 'globalBrief',
        c: 'ChartBrief',
        t: 'Global Brief',
        w: 3,
        h: 250,
      }, {
        d: 'globalPercent',
        c: 'ChartLine',
        t: 'Global Percent Response',
        w: '3',
        h: 250,
      }, {
        d: 'globalHeatmap',
        c: 'ChartHeatmap',
        t: 'Global Heatmap',
        w: 6,
        h: 250,
      }, {
        d: 'globalSlow',
        c: 'ChartSlow',
        t: 'Global Top Slow Endpoint',
        w: 6,
        h: '800',
      }, {
        o: 'Global',
        d: 'globalThroughput',
        c: 'ChartTrace',
        t: 'Global Top Throughput',
        w: '6',
        h: '800',
      }],
    }, {
      name: 'Service',
      children: [{
        o: 'Service',
        d: 'servicePercent',
        c: 'ChartLine',
        t: 'Service Percent Response',
        w: 3,
        h: '250',
      }, {
        o: 'Service',
        d: 'serviceThroughput',
        c: 'ChartNum',
        t: 'Service Avg Throughput',
        w: 3,
        h: 80,
      }, {
        o: 'Service',
        d: 'serviceSLA',
        c: 'ChartNum',
        t: 'Service Avg SLA',
        w: 3,
        h: 80,
      }, {
        o: 'Service',
        d: 'serviceResponseTime',
        c: 'ChartNum',
        t: 'Service Avg ResponseTime',
        w: 3,
        h: 80,
      }, {
        o: 'Service',
        d: 'serviceThroughput',
        c: 'ChartLine',
        t: 'Service Throughput',
        w: 3,
        h: 170,
      }, {
        o: 'Service',
        d: 'serviceSLA',
        c: 'ChartBar',
        t: 'Service SLA',
        w: 3,
        h: 170,
      }, {
        o: 'Service',
        d: 'serviceResponseTime',
        c: 'ChartLine',
        t: 'Service ResponseTime',
        w: 3,
        h: 170,
      }, {
        o: 'Service',
        d: 'serviceSlowEndpoint',
        c: 'ChartSlow',
        t: 'Service Slow Endpoint',
        w: '6',
        h: '500',
      }, {
        o: 'Service',
        d: 'serviceInstanceThroughput',
        c: 'ChartTrace',
        t: 'Running ServiceInstance',
        w: '6',
        h: '500',
      }],
    }, {
      name: 'Endpoint',
      children: [{
        o: 'ServiceEndpoint',
        d: 'endpointPercent',
        c: 'ChartLine',
        t: 'Endpoint Percent Response',
        w: 3,
        h: '250',
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointThroughput',
        c: 'ChartNum',
        t: 'Endpoint Avg Throughput',
        w: 3,
        h: 80,
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointSLA',
        c: 'ChartNum',
        t: 'Endpoint Avg SLA',
        w: 3,
        h: 80,
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointResponseTime',
        c: 'ChartNum',
        t: 'Endpoint Avg ResponseTime',
        w: 3,
        h: 80,
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointThroughput',
        c: 'ChartLine',
        t: 'Endpoint Throughput',
        w: 3,
        h: 170,
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointSLA',
        c: 'ChartBar',
        t: 'Endpoint SLA',
        w: 3,
        h: 170,
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointResponseTime',
        c: 'ChartLine',
        t: 'Endpoint ResponseTime',
        w: 3,
        h: 170,
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointTraces',
        c: 'ChartSlow',
        t: 'Endpoint Slow',
        w: 6,
        h: '500',
      }, {
        o: 'ServiceEndpoint',
        d: 'endpointTopology',
        c: 'ChartSankey',
        t: 'Dependency Map',
        w: 6,
        h: '500',
      }],
    }, {
      name: 'Instance',
      children: [{
        o: 'ServiceInstance',
        d: 'globalBrief',
        c: 'ChartInstance',
        t: 'Instance Info',
        w: 3,
        h: 250,
      }, {
        o: 'ServiceInstance',
        d: 'instanceResponseTime',
        c: 'ChartNum',
        t: 'Instance Avg ResponseTime',
        w: 3,
        h: '80',
      }, {
        o: 'ServiceInstance',
        d: 'instanceThroughput',
        c: 'ChartNum',
        t: 'Instance Avg Throughput',
        w: 3,
        h: '80',
      }, {
        o: 'ServiceInstance',
        d: 'instanceSLA',
        c: 'ChartNum',
        t: 'Instance Avg SLA',
        w: 3,
        h: '80',
      }, {
        o: 'ServiceInstance',
        d: 'instanceResponseTime',
        c: 'ChartLine',
        t: 'Instance ResponseTime',
        w: 3,
        h: '170',
      }, {
        o: 'ServiceInstance',
        d: 'instanceThroughput',
        c: 'ChartLine',
        t: 'Instance Throughput',
        w: 3,
        h: '170',
      }, {
        o: 'ServiceInstance',
        d: 'instanceSLA',
        c: 'ChartLine',
        t: 'Instance SLA',
        w: 3,
        h: '170',
      }, {
        o: 'ServiceInstance',
        d: 'instanceHeap',
        c: 'ChartLine',
        t: 'JVM Heap (MB)',
        w: 3,
        h: 250,
      }, {
        o: 'ServiceInstance',
        d: 'instanceNonheap',
        c: 'ChartLine',
        t: 'JVM Non-Heap (MB)',
        w: 3,
        h: 250,
      }, {
        o: 'ServiceInstance',
        d: 'instanceGC',
        c: 'ChartLine',
        t: 'JVM GC (ms)',
        w: 3,
        h: 250,
      }, {
        o: 'ServiceInstance',
        d: 'instanceGCCount',
        c: 'ChartCount',
        t: 'JVM GC Count',
        w: 3,
        h: '250',
      }, {
        o: 'ServiceInstance',
        d: 'instanceCPU',
        c: 'ChartLine',
        t: 'JVM CPU (%)',
        w: 3,
        h: 250,
      }],
    }],
  },
  1: {
    name: 'Database Dashboard',
    type: 'database',
    query: {
      service: {},
      endpoint: {},
      instance: {},
      database: {},
    },
    children: [{
      name: 'Global',
      children: [{
        d: 'globalBrief',
        c: 'ChartBrief',
        t: 'Global Brief',
        w: 3,
        h: 250,
      }, {
        d: 'globalPercent',
        c: 'ChartLine',
        t: 'Global Percent Response',
        w: '3',
        h: 250,
      }, {
        d: 'globalHeatmap',
        c: 'ChartHeatmap',
        t: 'Global Heatmap',
        w: 6,
        h: 250,
      }, {
        d: 'globalSlow',
        c: 'ChartSlow',
        t: 'Global Top Slow Endpoint',
        w: 6,
        h: '500',
      }, {
        o: 'Global',
        d: 'globalThroughput',
        c: 'ChartTrace',
        t: 'Global Top Throughput',
        w: '6',
        h: '500',
      }],
    }, {
      name: 'Database',
      children: [{
        o: 'Global',
        d: 'globalBrief',
        c: 'ChartBrief',
        t: 'Global Brief',
        w: 3,
        h: '250',
      }, {
        o: 'Database',
        d: 'databaseThroughput',
        c: 'ChartNum',
        t: 'Database Avg Throughput',
        w: 3,
        h: '80',
      }, {
        o: 'Database',
        d: 'databaseResponseTime',
        c: 'ChartNum',
        t: 'Database Avg ResponseTime',
        w: 3,
        h: '80',
      }, {
        o: 'Database',
        d: 'databaseSLA',
        c: 'ChartNum',
        t: 'Database Avg SLA',
        w: 3,
        h: 250,
      }, {
        o: 'Database',
        d: 'databaseThroughput',
        c: 'ChartLine',
        t: 'Database Throughput',
        w: 3,
        h: '250',
      }, {
        o: 'Database',
        d: 'databaseResponseTime',
        c: 'ChartLine',
        t: 'Database ResponseTime',
        w: 3,
        h: '250',
      }, {
        o: 'Database',
        d: 'databasePercent',
        c: 'ChartLine',
        t: 'Database Percent',
        w: 3,
        h: '250',
      }, {
        o: 'Database',
        d: 'databaseSLA',
        c: 'ChartBar',
        t: 'Database SLA',
        w: 3,
        h: '250',
      }, {
        o: 'Database',
        d: 'databaseTopNRecords',
        c: 'ChartSlow',
        t: 'Database TopN Records',
        w: '12',
        h: '800',
      }],
    }],
  },
};
